[project]
name = "sags-dash"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asgiref>=3.8.1",
    "dash-ag-grid>=31.3.0",
    "dash>=2.18.2",
    "polars>=1.16.0",
    "uvicorn>=0.32.1",
    "dash-table>=5.0.0",
    "flask-login>=0.6.3",
    "orjson>=3.10.12",
    "pydantic>=2.10.2",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "iso6709>=0.1.5",
    "pyproject-toml>=0.1.0",
    "plotly==6.0.0rc0",
    "numpy>=2.1.3",
]

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]


[tool.basedpyright]
typeCheckingMode = "basic"
venvPath = "."
venv = ".venv"
pythonVersion = "3.13"
useLibraryCodeForTypes = true

[tool.ruff]
select = ["E", "F", "T20", "I001"]
ignore = ["E402", "E501"]
fixable = ["E", "F", "I001"]

