// AUTOGENERATED FILE - DO NOT EDIT

var pt = window.PropTypes;
var pk = window['my_dash_component'];

pk.Container.propTypes = {children:pt.node,
 id:pt.string,
 setProps:pt.any};
pk.Grid.propTypes = {graths:pt.arrayOf(pt.node),
 selector:pt.node,
 hash:pt.string,
 id:pt.string,
 setProps:pt.any};
pk.Navbar.propTypes = {dashboard_name:pt.string,
 dashboard_picture:pt.string,
 dashboard_version:pt.string,
 is_admin:pt.bool,
 id:pt.string,
 setProps:pt.any};
